name: 'Terraform IaC'

on:
  push:
    branches:
      - dev
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

# OIDC permissions are required to allow the workflow to exchange a token with Azure.
permissions:
  id-token: write  # This is a key permission for OIDC.
  contents: read   # Allows the workflow to check out the repository code.

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Ensure this matches your local version

      - name: Terraform Init
        id: init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan -no-color

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} apply -auto-approve -input=false